// Reqruired Packages
let mongoose = require("mongoose");

// using packages
let Schema = mongoose.Schema;
let filterSchema = new Schema({
  brand: [],
  cc: [],
  bikeType: [],
  distributor: [],
  modelYear: [],
  brandOrigin: [],
  assembledIn: [],
  availableColorsArr: [],
  engineTypeArr: [],
  maxPowerValue: [],
  maxTorqueValue: [],
  strokeValue: [],
  valves: [],
  fuelSupply: [],
  noOfCylender: [],
  engineCool: [],
  startMethodArr: [],
  transmissionType: [],
  noOfGear: [],
  clutchTypeArr: [],
  driveType: [],
  mileageValue: [],
  topSpeedValue: [],
  chassisType: [],
  frontSuspension: [],
  rearSuspension: [],
  frontBrake: [],
  rearBrake: [],
  abs: [],
  frontTireSizeValue: [],
  rearTireSizeValue: [],
  tireType: [],
  wheelType: [],
  overallLengthValue: [],
  overallWidthValue: [],
  heightValue: [],
  groundClearanceValue: [],
  weightValue: [],
  fuleTankCapacityValue: [],
  wheelBaseValue: [],
  seatHeightValue: [],
  headLight: [],
  tailLight: [],
  indicator: [],
  speedoMeter: [],
  odoMeter: [],
  rpmMeter: [],
  handleType: [],
  seatType: [],
  passengerGrabRail: [],
  engineKillSwitch: [],
  additionalFeatureArr: [],
});
module.exports = mongoose.model("Filter", filterSchema);
